### ISSUE TITLE
css don't dsiplay other a:link background-image

### ISSUE THREAD

**Issue by ghost** [tenman/raindrops#6]
The Raindrops Theme CSS sets for `a:link a:visited a:..` the following `background-image: none;`
this pretents the plugins "Download Monitor" and "MimeTypes Link Icons" to display their file type icons.
Disabling the  `background-image: none;` looks first to fix this problem but then the header link text will become the same background color as the theme.
Only tested this with firefox page inspector.
**(but i can't find it the css files nor in the theme settings)**

``` css
a:link, a:active, a:visited, a:hover, #site-title, .h1 a {
color: #d0d0d0;
    background: none;
        background-color: transparent;
        background-image: none;
        background-repeat: repeat;
        background-attachment: scroll;
        background-position: 0% 0%;
        background-clip: border-box;
        background-origin: padding-box;
        background-size: auto auto;
}
```

Is there anyway to get this to work ?
ps: with another theme is there no problem
